### ISSUE TITLE
Test project name convention

### ISSUE THREAD

**Issue by piecioshka** [robreczarek/test-js-practice-zoo#1]
Please rename project name.
Add prefix "test-" to each test project.

Btw. For project names use always "snake-case" convention.

**Comment by robreczarek** [comment]
Snake case convention has been committed to master.

**Comment by piecioshka** [comment]
But project on GitHub is still not in convention ("jspractice" => "test-js-practice-zoo")

**Comment by robreczarek** [comment]
@piecioshka Got it. I'm re-opening this issue and will rename accordingly.

**Comment by piecioshka** [comment]
Thanks. This convention will helps you to organize a lot of projects in your workspace.
