### ISSUE TITLE
Where are constructors?

### ISSUE THREAD

**Issue by piecioshka** [robreczarek/test-js-practice-zoo#2]
Missing:

* Animal
* Elephant
* Lion

**Comment by robreczarek** [comment]
@piecioshka All three objects are now present. Is there something that should be changed in the animal object?

**Comment by piecioshka** [comment]
Constructor in JS are:

```js
function Animal() {
  //...
}
Animal.prototype.xxx = function () {
  // ...
}
```

:)

**Comment by robreczarek** [comment]
@piecioshka I have revised the code, but am running into issues. Can you please take a look at commit #7 

My intent was to mix things up to have properties that are assigned during object instantiation, ones that are private to the internal object, and ones that are exposed via "public" properties. 

I'm not sure why I'm not able to push animal objects via the addAnimal method. Also, why do the getGroup and getDiet properties return the function body and not the literals for each?

**Comment by piecioshka** [comment]
@robreczarek nie dam rady chyba po ang to wytłumaczyć 😄  ale spróbuje...

When you defined:

```js
var animals = [];
```

this is a local variable. So the scope of access starts at 1 line of index.js file and ends in 5 line (when brackets ends).

You should make `animals` as object member.

```js
this.animals = [];
```

And in each "method" you should use `this` as reference to object instance. eg

```js
return this.animals.push(animal);
```

**Comment by piecioshka** [comment]
@robreczarek btw. please make seconds file `test.js` where you import `index.js` file (by require global function) and move whole console.log block to it.

**Comment by robreczarek** [comment]
@piecioshka Możemy też po polsku. Powiedzmy że będzie mi szło raczej koślawo ;)

Usunąłem var i zamieniłem na this, ale nadal mam problem z tym że wypluwa mi funkcję zamiast wartości.

No i teraz jak mam test w oddzielnym pliku, to nie wiem jak zrobić żeby odpaliło. Wyskakują mi ReferenceError.

Probowałem też 
`var index = require('./index.js');`

I w console.log
`console.log( 'Welcome to ' + index.myzoo.zooName );`

Ale też mam wtedy ReferenceError

**Comment by piecioshka** [comment]
@robreczarek nie nie, piszemy po angielsku 😄 

I was created Pull Request with some changes: https://github.com/robreczarek/test-js-practice-zoo/pull/4
Please review it.

**Comment by robreczarek** [comment]
@piecioshka I see that you added object definitions for Lion and Elephant, plus a section for module.exports. 

This is to expose them for consumption when you require a file, correct? Is this a node.js specific thing?

**Comment by piecioshka** [comment]
This is called "CommonJS syntax".
In definition file you `exports`, and in setup file you `require`.

**Comment by robreczarek** [comment]
@piecioshka Got it. Gonna read up on the spec. Seems like this part is a wrap, so I'm closing this out.
